<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.sonatype.oss</groupId>
    <artifactId>oss-parent</artifactId>
    <version>7</version>
  </parent>

  <groupId>io.hops.hive</groupId>
  <artifactId>hive-apache</artifactId>
  <version>4.1.0-1</version>

  <name>hive-apache</name>
  <description>Shaded version of Apache Hive for Trino</description>
  <url>https://github.com/trinodb/trino-hive-apache</url>

  <inceptionYear>2013</inceptionYear>

  <licenses>
    <license>
      <name>Apache License 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <!-- see original projects for developer information -->
  </developers>

  <scm>
    <connection>scm:git:git://github.com/trinodb/trino-hive-apache.git</connection>
    <developerConnection>scm:git:git://github.com/trinodb/trino-hive-apache.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/trinodb/trino-hive-apache</url>
  </scm>

  <distributionManagement>
    <repository>
      <id>HopsEE</id>
      <name>Hops Repo</name>
      <url>https://nexus.hops.works/repository/hive-artifacts</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </distributionManagement>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.build.targetJdk>17</project.build.targetJdk>

    <shadeBase>io.trino.hive.\$internal</shadeBase>

    <dep.hive.version>4.1.0</dep.hive.version>

    <dep.avro.version>1.10.2</dep.avro.version>
    <dep.hadoop.version>3.4.3.2-EE-RC0</dep.hadoop.version>
    <dep.parquet.version>1.12.3</dep.parquet.version>
    <dep.protobuf.version>2.5.0</dep.protobuf.version>
    <dep.slf4j.version>1.7.29</dep.slf4j.version>
  </properties>

  <dependencies>
    <!-- discard logging from hive -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
      <version>${dep.slf4j.version}</version>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-nop</artifactId>
      <version>${dep.slf4j.version}</version>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${dep.slf4j.version}</version>
    </dependency>

    <!-- hive -->
    <dependency>
      <groupId>io.hops.hive</groupId>
      <artifactId>hive-metastore</artifactId>
      <version>${dep.hive.version}</version>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.hops.hive</groupId>
      <artifactId>hive-standalone-metastore-server</artifactId>
      <version>${dep.hive.version}</version>
      <exclusions>
        <exclusion>
          <groupId>io.airlift</groupId>
          <artifactId>aircompressor</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-metastore</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-hdfs</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.github.joshelser</groupId>
          <artifactId>dropwizard-metrics-hadoop-metrics2-reporter</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-1.2-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-slf4j-impl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.httpcomponents</groupId>
          <artifactId>httpcore</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.httpcomponents</groupId>
          <artifactId>httpclient</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javolution</groupId>
          <artifactId>javolution</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.jolbox</groupId>
          <artifactId>bonecp</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.zaxxer</groupId>
          <artifactId>HikariCP</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-dbcp</groupId>
          <artifactId>commons-dbcp</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.derby</groupId>
          <artifactId>derby</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.datanucleus</groupId>
          <artifactId>javax.jdo</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.datanucleus</groupId>
          <artifactId>datanucleus-api-jdo</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.datanucleus</groupId>
          <artifactId>datanucleus-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.datanucleus</groupId>
          <artifactId>datanucleus-rdbms</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.antlr</groupId>
          <artifactId>antlr-runtime</artifactId>
        </exclusion>
        <exclusion>
          <groupId>sqlline</groupId>
          <artifactId>sqlline</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-context-log4j2</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-httpclient</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-common-protos</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-iam-v1</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>azure-data-lake-store-sdk</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-all</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.htrace</groupId>
          <artifactId>htrace-core4</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-zipkin</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.zipkin2</groupId>
          <artifactId>zipkin</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.hops.hive</groupId>
      <artifactId>hive-serde</artifactId>
      <version>${dep.hive.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-service-rpc</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-upgrade-acid</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-yarn-server-resourcemanager</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.arrow</groupId>
          <artifactId>arrow-vector</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.parquet</groupId>
          <artifactId>parquet-hadoop-bundle</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.carrotsearch</groupId>
          <artifactId>hppc</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.vlkan</groupId>
          <artifactId>flatbuffers</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.curator</groupId>
          <artifactId>curator-framework</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.zookeeper</groupId>
          <artifactId>zookeeper</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-slf4j-impl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.code.findbugs</groupId>
          <artifactId>jsr305</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-context-log4j2</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-httpclient</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-common-protos</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-iam-v1</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>azure-data-lake-store-sdk</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-all</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.htrace</groupId>
          <artifactId>htrace-core4</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-zipkin</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.zipkin2</groupId>
          <artifactId>zipkin</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.hops.hive</groupId>
      <artifactId>hive-exec</artifactId>
      <version>${dep.hive.version}</version>
      <classifier>core</classifier>
      <exclusions>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-ant</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-llap-tez</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-upgrade-acid</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-vector-code-gen</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-yarn-registry</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-1.2-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-slf4j-impl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.zookeeper</groupId>
          <artifactId>zookeeper</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.curator</groupId>
          <artifactId>apache-curator</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.curator</groupId>
          <artifactId>curator-framework</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.calcite</groupId>
          <artifactId>calcite-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.calcite</groupId>
          <artifactId>calcite-druid</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.calcite.avatica</groupId>
          <artifactId>avatica</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.datanucleus</groupId>
          <artifactId>datanucleus-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.ant</groupId>
          <artifactId>ant</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.ivy</groupId>
          <artifactId>ivy</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-io</groupId>
          <artifactId>commons-io</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.commons</groupId>
          <artifactId>commons-compress</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.antlr</groupId>
          <artifactId>antlr-runtime</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.antlr</groupId>
          <artifactId>ST4</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-all</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.code.gson</groupId>
          <artifactId>gson</artifactId>
        </exclusion>
        <exclusion>
          <groupId>stax</groupId>
          <artifactId>stax-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-context-log4j2</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-httpclient</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-common-protos</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-iam-v1</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>azure-data-lake-store-sdk</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-all</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.htrace</groupId>
          <artifactId>htrace-core4</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-zipkin</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.zipkin2</groupId>
          <artifactId>zipkin</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.hops.hive</groupId>
      <artifactId>hive-common</artifactId>
      <version>${dep.hive.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-service-rpc</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-upgrade-acid</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-hdfs</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.github.joshelser</groupId>
          <artifactId>dropwizard-metrics-hadoop-metrics2-reporter</artifactId>
        </exclusion>
        <exclusion>
          <groupId>jline</groupId>
          <artifactId>jline</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.servlet</groupId>
          <artifactId>javax.servlet-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.jetty</groupId>
          <artifactId>jetty-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.jetty</groupId>
          <artifactId>jetty-rewrite</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.jetty</groupId>
          <artifactId>jetty-server</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.jetty</groupId>
          <artifactId>jetty-servlet</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.jetty</groupId>
          <artifactId>jetty-webapp</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javolution</groupId>
          <artifactId>javolution</artifactId>
        </exclusion>
        <exclusion>
          <groupId>net.sf.jpam</groupId>
          <artifactId>jpam</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.ant</groupId>
          <artifactId>ant</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-1.2-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-slf4j-impl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-web</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.commons</groupId>
          <artifactId>commons-compress</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-cli</groupId>
          <artifactId>commons-cli</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-context-log4j2</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-instrumentation-httpclient</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-common-protos</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-iam-v1</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>azure-data-lake-store-sdk</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-all</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.htrace</groupId>
          <artifactId>htrace-core4</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.brave</groupId>
          <artifactId>brave-zipkin</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.zipkin.zipkin2</groupId>
          <artifactId>zipkin</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.hops.hive.hcatalog</groupId>
      <artifactId>hive-hcatalog-core</artifactId>
      <version>${dep.hive.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-cli</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-exec</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-metastore</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-upgrade-acid</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-annotations</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-archives</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-mapreduce-client-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-hdfs</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- include missing dependencies -->
    <dependency>
      <groupId>org.apache.parquet</groupId>
      <artifactId>parquet-common</artifactId>
      <version>${dep.parquet.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.yetus</groupId>
          <artifactId>audience-annotations</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.apache.parquet</groupId>
      <artifactId>parquet-column</artifactId>
      <version>${dep.parquet.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.yetus</groupId>
          <artifactId>audience-annotations</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.apache.parquet</groupId>
      <artifactId>parquet-hadoop</artifactId>
      <version>${dep.parquet.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.yetus</groupId>
          <artifactId>audience-annotations</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.github.luben</groupId>
          <artifactId>zstd-jni</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.xerial.snappy</groupId>
          <artifactId>snappy-java</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-pool</groupId>
          <artifactId>commons-pool</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.apache.parquet</groupId>
      <artifactId>parquet-avro</artifactId>
      <version>${dep.parquet.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.avro</groupId>
      <artifactId>avro</artifactId>
      <version>${dep.avro.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.thoughtworks.paranamer</groupId>
          <artifactId>paranamer</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.xerial.snappy</groupId>
          <artifactId>snappy-java</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.apache.avro</groupId>
      <artifactId>avro-mapred</artifactId>
      <version>${dep.avro.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.avro</groupId>
          <artifactId>avro-ipc</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.avro</groupId>
          <artifactId>avro-ipc-jetty</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>${dep.protobuf.version}</version>
    </dependency>

    <dependency>
      <groupId>org.codehaus.jackson</groupId>
      <artifactId>jackson-mapper-asl</artifactId>
      <version>1.9.13</version>
    </dependency>

    <!-- Hadoop compilation dependencies -->
    <dependency>
      <groupId>io.hops</groupId>
      <artifactId>hadoop-common</artifactId>
      <version>${dep.hadoop.version}</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.hops</groupId>
      <artifactId>hadoop-mapreduce-client-core</artifactId>
      <version>${dep.hadoop.version}</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>interval:15</updatePolicy>
      </snapshots>
      <id>HopsEE</id>
      <name>Hops Release Repository</name>
      <url>https://nexus.hops.works/repository/hops-artifacts</url>
    </repository>
    <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>interval:15</updatePolicy>
      </snapshots>
      <id>HiveEE</id>
      <name>Hive Release Repository</name>
      <url>https://nexus.hops.works/repository/hive-artifacts</url>
    </repository>
  </repositories>

  <build>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>2.5</version>
          <configuration>
            <mavenExecutorId>forked-path</mavenExecutorId>
            <pushChanges>false</pushChanges>
            <localCheckout>true</localCheckout>
            <useReleaseProfile>false</useReleaseProfile>
            <preparationGoals>clean install</preparationGoals>
            <autoVersionSubmodules>true</autoVersionSubmodules>
            <tagNameFormat>@{project.version}</tagNameFormat>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>1.4</version>
          <configuration>
            <useAgent>true</useAgent>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>2.9</version>
          <configuration>
            <source>${project.build.targetJdk}</source>
            <additionalparam>-quiet</additionalparam>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>1.2</version>
        <configuration>
          <rules>
            <requireJavaVersion>
              <version>${project.build.targetJdk}</version>
            </requireJavaVersion>
          </rules>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>enforce</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>${project.build.targetJdk}</source>
          <target>${project.build.targetJdk}</target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.12.4</version>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>2.2.1</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <execution>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <createSourcesJar>true</createSourcesJar>
              <shadeSourcesContent>true</shadeSourcesContent>
              <dependencyReducedPomLocation>${project.build.directory}/pom.xml</dependencyReducedPomLocation>
              <promoteTransitiveDependencies>true</promoteTransitiveDependencies>
              <artifactSet>
                <excludes>
                  <exclude>joda-time:joda-time</exclude>
                  <exclude>org.apache.thrift:libthrift</exclude>
                  <exclude>org.apache.avro:*</exclude>
                  <exclude>org.apache.parquet:*</exclude>
                  <exclude>io.airlift:aircompressor</exclude>
                  <!-- Server-side deps leaking in (unrelocated) via
                       hive-standalone-metastore-server / hive-exec; Trino only uses the
                       wrapper for serdes, metastore thrift beans and Acid/Txn utils in
                       tests, none of which touch the ObjectStore, ZK locking or curator. -->
                  <exclude>org.datanucleus:*</exclude>
                  <exclude>org.apache.zookeeper:*</exclude>
                  <exclude>org.apache.curator:*</exclude>
                </excludes>
              </artifactSet>
              <relocations>
                <relocation>
                  <pattern>org.apache.orc</pattern>
                  <shadedPattern>io.trino.hive.orc</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>com.google.protobuf</pattern>
                  <shadedPattern>${shadeBase}.com.google.protobuf</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>org.apache.commons</pattern>
                  <shadedPattern>${shadeBase}.org.apache.commons</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>com.facebook.fb303</pattern>
                  <shadedPattern>${shadeBase}.com.facebook.fb303</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>com.google.common</pattern>
                  <shadedPattern>${shadeBase}.com.google.common</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>com.google.thirdparty</pattern>
                  <shadedPattern>${shadeBase}.com.google.thirdparty</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>org.objectweb.asm</pattern>
                  <shadedPattern>${shadeBase}.org.objectweb.asm</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>org.objenesis</pattern>
                  <shadedPattern>${shadeBase}.org.objenesis</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>org.codehaus.jackson</pattern>
                  <shadedPattern>${shadeBase}.org.codehaus.jackson</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>com.fasterxml.jackson</pattern>
                  <shadedPattern>${shadeBase}.com.fasterxml.jackson</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>org.json</pattern>
                  <shadedPattern>${shadeBase}.org.json</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>au.com.bytecode.opencsv</pattern>
                  <shadedPattern>${shadeBase}.au.com.bytecode.opencsv</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>com.codahale.metrics</pattern>
                  <shadedPattern>${shadeBase}.com.codahale.metrics</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>org.slf4j</pattern>
                  <shadedPattern>${shadeBase}.org.slf4j</shadedPattern>
                </relocation>
              </relocations>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/maven/**</exclude>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>org.slf4j:*</artifact>
                  <excludes>
                    <exclude>META-INF/services/**</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>org.apache.hive:hive-common</artifact>
                  <excludes>
                    <exclude>hive-log4j2.properties</exclude>
                    <exclude>parquet-logging.properties</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>org.apache.hive:hive-exec</artifact>
                  <excludes>
                    <exclude>META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat</exclude>
                    <exclude>hive-exec-log4j2.properties</exclude>
                    <exclude>tez-container-log4j2.properties</exclude>
                    <exclude>org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.class</exclude>
                    <exclude>org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader$*.class</exclude>
                    <exclude>org/apache/hadoop/hive/ql/io/CodecPool.class</exclude>
                    <exclude>org/apache/hadoop/hive/ql/io/CodecPool$*.class</exclude>
                    <exclude>org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.class</exclude>
                    <exclude>org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils$*.class</exclude>
                    <exclude>org/apache/tez/**</exclude>
                    <!-- Exclude all embedded Parquet classes -->
                    <exclude>org/apache/parquet/**</exclude>
                    <exclude>parquet/**</exclude>
                    <exclude>shaded/parquet/**</exclude>
                    <!-- Exclude conflicting resource files -->
                    <exclude>**/*.proto</exclude>
                    <exclude>parquet.thrift</exclude>
                    <exclude>parquet_types.thrift</exclude>
                    <exclude>google/**/*.proto</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>io.hops.hive:hive-standalone-metastore-server</artifact>
                  <excludes>
                    <exclude>package.jdo</exclude>
                    <exclude>org/apache/hadoop/hive/metastore/api/**</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>org.apache.hive:hive-serde</artifact>
                  <excludes>
                    <exclude>org/apache/hadoop/hive/serde2/avro/AvroDeserializer.class</exclude>
                    <exclude>org/apache/hadoop/hive/serde2/avro/AvroDeserializer$*.class</exclude>
                    <exclude>org/apache/hadoop/hive/serde2/avro/InstanceCache.class</exclude>
                    <exclude>org/apache/hadoop/hive/serde2/avro/InstanceCache$*.class</exclude>
                    <exclude>org/apache/hadoop/hive/serde2/avro/SchemaToTypeInfo.class</exclude>
                    <exclude>org/apache/hadoop/hive/serde2/avro/SchemaToTypeInfo$*.class</exclude>
                    <exclude>org/apache/hadoop/hive/serde2/avro/TypeInfoToSchema.class</exclude>
                    <exclude>org/apache/hadoop/hive/serde2/avro/TypeInfoToSchema$*.class</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>org.apache.hive.hcatalog:hive-hcatalog-core</artifact>
                  <excludes>
                    <exclude>org/apache/hive/hcatalog/data/JsonSerDe.class</exclude>
                    <exclude>org/apache/hive/hcatalog/data/JsonSerDe$*.class</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>org.apache.avro:avro</artifact>
                  <excludes>
                    <exclude>overview.html</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>org.apache.commons:commons-lang3</artifact>
                  <excludes>
                    <exclude>templates/release-notes.vm</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>com.fasterxml.jackson.core:*</artifact>
                  <excludes>
                    <exclude>META-INF/services/**</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <!-- Exclude duplicate Brave tracing classes -->
                    <exclude>brave/**</exclude>
                    <!-- Exclude all repackaged classes to avoid duplicates -->
                    <exclude>com/lc/repackaged/**</exclude>
                    <!-- Exclude Microsoft shaded classes -->
                    <exclude>com/microsoft/shaded/**</exclude>
                    <!-- Exclude shaded Netty classes -->
                    <exclude>org/apache/hadoop/shaded/**</exclude>
                    <!-- Exclude HTrace shaded classes -->
                    <exclude>org/apache/htrace/shaded/**</exclude>
                    <!-- Exclude HTrace core classes -->
                    <exclude>org/apache/htrace/core/**</exclude>
                    <!-- Exclude Zipkin tracing classes -->
                    <exclude>zipkin2/**</exclude>
                    <!-- Exclude conflicting Hops classes - keep from Hadoop dependency only -->
                    <exclude>io/hops/**</exclude>
                    <!-- Exclude Hadoop classes but keep Hive-specific ones -->
                    <exclude>org/apache/hadoop/classification/**</exclude>
                    <exclude>org/apache/hadoop/fs/**</exclude>
                    <exclude>org/apache/hadoop/hdfs/**</exclude>
                    <exclude>org/apache/hadoop/conf/**</exclude>
                    <exclude>org/apache/hadoop/io/**</exclude>
                    <exclude>org/apache/hadoop/util/**</exclude>
                    <exclude>org/apache/hadoop/security/**</exclude>
                    <exclude>org/apache/hadoop/net/**</exclude>
                    <exclude>org/apache/hadoop/ipc/**</exclude>
                    <exclude>org/apache/hadoop/crypto/**</exclude>
                    <exclude>org/apache/hadoop/metrics/**</exclude>
                    <exclude>org/apache/hadoop/yarn/**</exclude>
                    <exclude>org/apache/hadoop/mapred/**</exclude>
                    <exclude>org/apache/hadoop/mapreduce/**</exclude>
                    <exclude>org/apache/hadoop/tools/**</exclude>
                    <exclude>org/apache/hadoop/service/**</exclude>
                    <exclude>org/apache/hadoop/log/**</exclude>
                    <!-- Keep org/apache/hadoop/hive/** - this is needed for Hive functionality -->
                    <!-- Exclude ALL third-party libraries that conflict with Trino dependencies -->
                    <!-- Exclude Netty libraries -->
                    <exclude>io/netty/**</exclude>
                    <!-- Exclude Google libraries -->
                    <exclude>com/google/common/**</exclude>
                    <exclude>com/google/inject/**</exclude>
                    <exclude>com/google/errorprone/**</exclude>
                    <exclude>com/google/j2objc/**</exclude>
                    <exclude>com/google/protobuf/**</exclude>
                    <exclude>com/google/gson/**</exclude>
                    <!-- Exclude Apache Avro -->
                    <exclude>org/apache/avro/**</exclude>
                    <!-- Exclude Apache Parquet - but this seems to not be working fully -->
                    <exclude>org/apache/parquet/**</exclude>
                    <exclude>parquet/**</exclude>
                    <exclude>shaded/parquet/**</exclude>
                    <!-- Exclude Apache Thrift -->
                    <exclude>org/apache/thrift/**</exclude>
                    <!-- Exclude logging libraries -->
                    <exclude>org/slf4j/**</exclude>
                    <exclude>org/apache/logging/**</exclude>
                    <exclude>org/apache/log4j/**</exclude>
                    <!-- Exclude Joda Time -->
                    <exclude>org/joda/**</exclude>
                    <!-- Exclude Checker Framework -->
                    <exclude>org/checkerframework/**</exclude>
                    <!-- Exclude AOP Alliance -->
                    <exclude>org/aopalliance/**</exclude>
                    <!-- Exclude javax annotations -->
                    <exclude>javax/**</exclude>
                    <!-- Exclude JLine command line library -->
                    <exclude>org/jline/**</exclude>
                    <!-- Exclude Args4j argument parsing library -->
                    <exclude>org/kohsuke/args4j/**</exclude>
                    <!-- Exclude XML encoding library -->
                    <exclude>org/znerd/xmlenc/**</exclude>
                    <!-- Exclude additional third-party libraries found in Hive fat JAR -->
                    <!-- Exclude JCommander -->
                    <exclude>com/beust/jcommander/**</exclude>
                    <!-- Exclude ESRI Geometry -->
                    <exclude>com/esri/**</exclude>
                    <!-- Exclude Nimbus libraries -->
                    <exclude>com/nimbusds/**</exclude>
                    <!-- Exclude JNA -->
                    <exclude>com/sun/jna/**</exclude>
                    <!-- Exclude Jersey/JAX-RS -->
                    <exclude>org/glassfish/jersey/**</exclude>
                    <exclude>org/glassfish/hk2/**</exclude>
                    <exclude>com/sun/research/ws/wadl/**</exclude>
                    <exclude>jersey/repackaged/**</exclude>
                    <!-- Exclude Jetty -->
                    <exclude>org/eclipse/jetty/**</exclude>
                    <!-- Exclude OkHttp/OkIO -->
                    <exclude>okhttp3/**</exclude>
                    <exclude>okio/**</exclude>
                    <!-- Exclude Javassist -->
                    <exclude>javassist/**</exclude>
                    <!-- Exclude JUnit -->
                    <exclude>junit/**</exclude>
                    <!-- Exclude JSON libraries -->
                    <exclude>net/minidev/**</exclude>
                    <!-- Exclude JCIP annotations -->
                    <exclude>net/jcip/**</exclude>
                    <!-- Exclude Aircompressor -->
                    <exclude>io/airlift/compress/**</exclude>
                    <!-- Exclude additional Sun/Oracle libraries -->
                    <exclude>com/sun/istack/**</exclude>
                    <exclude>com/sun/xml/**</exclude>
                    <exclude>org/jvnet/**</exclude>
                    <!-- Exclude AWS SDK -->
                    <exclude>com/amazonaws/**</exclude>
                    <!-- Exclude Azure SDK -->
                    <exclude>com/azure/**</exclude>
                    <exclude>com/microsoft/aad/**</exclude>
                    <!-- Exclude Reactive Libraries -->
                    <exclude>reactor/**</exclude>
                    <exclude>io/projectreactor/**</exclude>
                    <!-- Exclude gRPC -->
                    <exclude>io/grpc/**</exclude>
                    <!-- Exclude OpenCensus -->
                    <exclude>io/opencensus/**</exclude>
                    <!-- Exclude Apache HTTP -->
                    <exclude>org/apache/http/**</exclude>
                    <!-- Exclude Woodstox XML -->
                    <exclude>com/ctc/wstx/**</exclude>
                    <exclude>org/codehaus/stax2/**</exclude>
                    <!-- Exclude ThreeTen Time -->
                    <exclude>org/threeten/bp/**</exclude>
                    <!-- Exclude Reactive Streams -->
                    <exclude>org/reactivestreams/**</exclude>
                    <!-- Exclude Apache Calcite -->
                    <exclude>org/apache/calcite/**</exclude>
                    <!-- Exclude Animal Sniffer -->
                    <exclude>org/codehaus/mojo/animal_sniffer/**</exclude>
                    <!-- Exclude conflicting resources -->
                    <exclude>META-INF/services/org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor</exclude>
                    <exclude>**/*.proto</exclude>
                    <exclude>log4j*.properties</exclude>
                    <exclude>Log4j-charsets.properties</exclude>
                    <exclude>parquet.thrift</exclude>
                    <exclude>parquet_types.thrift</exclude>
                    <exclude>**/parquet/**/*.proto</exclude>
                    <exclude>**/google/protobuf/**</exclude>
                    <!-- Exclude Hadoop configuration files -->
                    <exclude>hdfs-default.xml</exclude>
                    <exclude>erasure-coding-default.xml</exclude>
                    <exclude>storage.v1.json</exclude>
                    <!-- Exclude JLine resource files -->
                    <exclude>org/jline/**/*.txt</exclude>
                    <exclude>org/jline/**/*.caps</exclude>
                    <exclude>org/jline/**/*.properties</exclude>
                    <!-- Exclude Args4j resource files -->
                    <exclude>org/kohsuke/args4j/**/*.properties</exclude>
                    <!-- Exclude additional resource files -->
                    <exclude>com/esri/**/*.txt</exclude>
                    <exclude>com/sun/jna/**/*.template</exclude>
                    <exclude>com/sun/jna/**/*.so</exclude>
                    <exclude>com/sun/jna/**/*.a</exclude>
                    <exclude>com/sun/jna/**/*.dll</exclude>
                    <exclude>junit/**/*.gif</exclude>
                    <exclude>org/eclipse/jetty/**/*.properties</exclude>
                    <exclude>org/glassfish/**/*.properties</exclude>
                    <exclude>assets/**/*.properties</exclude>
                    <exclude>assets/**/*</exclude>
                    <exclude>tables/**/*.bin</exclude>
                    <!-- Exclude additional resource files -->
                    <exclude>com/amazonaws/**/*.json</exclude>
                    <exclude>com/amazonaws/**/*.properties</exclude>
                    <exclude>azure-*.properties</exclude>
                    <exclude>com/ctc/wstx/**/*.properties</exclude>
                    <exclude>org/apache/calcite/**/*.properties</exclude>
                    <exclude>org/apache/http/**/*.properties</exclude>
                    <exclude>org/threeten/bp/**/*.dat</exclude>
                    <exclude>org/threeten/bp/**/*.properties</exclude>
                    <exclude>dependencies.properties</exclude>
                    <exclude>mime.types</exclude>
                    <exclude>mozilla/public-suffix-list.txt</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
